# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Optical Research Collective
email: cdodson@optrescol.org
description: >- # this means to ignore newlines until "baseurl:"
  We are a collective of scientists and engineers enabling low-cost, compact, and robust optical sensing platforms and computational tools. Our goal is to provide an inclusive environment for the development of researchers and their scientific pursuits. We believe in a horizontal structure with all members holding equal voice. Research directions are to be developed independently by members with the support of the collective.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.optrescol.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  dodson-c

# Build settings
theme: neuromorphism
plugins:
  - jekyll-feed
# include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
